from rsf.proj import *

Flow('marmref','marmvel','deriv')
Result('marmref','grey')

nshots = 38
incShots = 8


Flow('seismicData','marmvel marmref',
"""./mod incShots=8 incRec=0 nshots=38 nr=368 isrc=0 jsrc=34 gxbeg=0 ref=${SOURCES[1]} vel=${SOURCES[0]} data=${TARGETS[0]} """,stdout=0)

Result('seismicData', "grey gainpanel=a")

End()
